{{- range $name, $role := .Values.extraRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
subjects:
  {{- toYaml $role.subjects | nindent 2 }}
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: {{ $name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}