{{- range $name, $role := .Values.extraRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
    {{- toYaml $role.resources | nindent 4 }}
  verbs:
    {{- toYaml $role.verbs | nindent 4 }}
{{- end }}